import assert from 'node:assert/strict';
import {root, data, api, patch} from '../src/firestore';
import {put, read, connectionPath, saveCandidate} from '../src/mail/storage';
import {mailRoute} from '../src/mail/routes';
const pair=await crypto.subtle.generateKey({name:'RSASSA-PKCS1-v1_5',modulusLength:2048,publicExponent:new Uint8Array([1,0,1]),hash:'SHA-256'},true,['sign','verify']);
const env={FIREBASE_PROJECT_ID:'demo-nexo-sync',FIREBASE_API_KEY:'fake',FIREBASE_CLIENT_EMAIL:'fake@example.test',FIREBASE_PRIVATE_KEY:`-----BEGIN PRIVATE KEY-----\n${Buffer.from(await crypto.subtle.exportKey('pkcs8',pair.privateKey)).toString('base64')}\n-----END PRIVATE KEY-----`,MAIL_ENCRYPTION_KEY:'ab'.repeat(32),GMAIL_CLIENT_ID:'test',GMAIL_CLIENT_SECRET:'test',GMAIL_REDIRECT_URI:'https://test.example/mail/gmail/callback'};
const original=globalThis.fetch;
globalThis.fetch=async(url,init={})=>{const parsed=new URL(String(url));if(parsed.hostname==='oauth2.googleapis.com')return Response.json({access_token:'emulator',expires_in:3600});if(parsed.hostname==='firestore.googleapis.com')return original('http://127.0.0.1:8080'+parsed.pathname+parsed.search,{...init,headers:{...init.headers,Authorization:'Bearer owner'}});throw Error('Unexpected network host');};
const uid='mail-test-'+Date.now();
const connection=await put(env,connectionPath(env,uid,'gmail'),{uid,provider:'gmail',address:'test@example.test',secret:'never-expose',timeZone:'America/Sao_Paulo'});
const message={id:'1',threadId:'thread',from:'clinic@example.test',subject:'Consulta',text:'',receivedAt:'2026-09-27T12:00:00Z'};
const candidate={title:'Consulta',notes:'Clínica',startsAt:'2026-09-30T14:00:00Z'};
assert.equal(await saveCandidate(env,connection,message,candidate),true);
assert.equal(await saveCandidate(env,connection,message,candidate),false);
assert.equal(await saveCandidate(env,connection,{...message,id:'duplicate'},candidate),false);
const collection=await api(env,`${root(env)}/users/${uid}/data`);assert.equal(collection.documents.length,1);
let record=collection.documents[0];const id=data(record).id;
const mirror=await read(env,`${root(env)}/users/${uid}/reminders/${id}`);assert.equal(data(mirror!).title,'Gmail: Consulta');
assert.equal(await saveCandidate(env,connection,{...message,id:'new',receivedAt:'2026-09-28T12:00:00Z'},{...candidate,startsAt:'2026-10-01T14:00:00Z'}),true);
record=await read(env,record.name);assert.equal(data(record).revision,2);
assert.equal(await saveCandidate(env,connection,{...message,id:'old',receivedAt:'2026-09-26T12:00:00Z'},{...candidate,startsAt:'2026-10-02T14:00:00Z'}),false);
record=await patch(env,record,{payload:{...data(record).payload,title:'Meu título'}});
assert.equal(await saveCandidate(env,connection,{...message,id:'edited',receivedAt:'2026-09-29T12:00:00Z'},{...candidate,startsAt:'2026-10-03T14:00:00Z'}),false);
record=await patch(env,record,{deleted:true,payload:null});
assert.equal(await saveCandidate(env,connection,{...message,id:'deleted',receivedAt:'2026-09-29T12:00:00Z'},{...candidate,startsAt:'2026-10-04T14:00:00Z'}),false);
const status=await mailRoute(new Request('https://test/mail/status'),env,uid);assert(!JSON.stringify(status).includes('never-expose'));
const other=await mailRoute(new Request('https://test/mail/status'),env,'another-user') as any;assert.equal(other.connections.length,0);
const request=(path,body)=>new Request('https://test/mail/'+path,{method:'POST',body:JSON.stringify(body)});
const started=await mailRoute(request('gmail/start',{browserSecret:'a'.repeat(43),timeZone:'America/Sao_Paulo'}),env,uid) as any;
const state=new URL(started.url).searchParams.get('state');
await assert.rejects(mailRoute(request('gmail/finish',{state,code:'test',browserSecret:'a'.repeat(43)}),env,'another-user'),/outra sessão/);
await assert.rejects(mailRoute(request('gmail/finish',{state,code:'test',browserSecret:'b'.repeat(43)}),env,uid),/outra sessão/);
await api(env,connection.name,{method:'DELETE'});
await assert.rejects(saveCandidate(env,connection,{...message,id:'after-disconnect',threadId:'new-thread'},{...candidate,title:'Outro compromisso'}));
console.log('PASS real Firestore mail import, mirror, deduplication, revision, user edits, tombstones, disconnect race, account isolation and OAuth CSRF');
