import {fileURLToPath} from 'node:url';
import {chromium} from 'playwright';
import assert from 'node:assert/strict';import fs from 'node:fs';import {seed} from './qa-seed.mjs';
process.chdir(fileURLToPath(new URL('../', import.meta.url)));
fs.mkdirSync('qa/artifacts/screens',{recursive:true});
const browser=await chromium.launch({headless:true,...(process.env.NEXO_TEST_BROWSER ? {executablePath:process.env.NEXO_TEST_BROWSER} : {})});const page=await browser.newPage({viewport:{width:1440,height:1000}});const results=[];
async function check(name,fn){await fn();results.push({name,status:'pass'});console.log('PASS',name)}
await page.goto('http://127.0.0.1:4174');await page.locator('h1').waitFor();await seed(page);
for(const width of [320,390,768,1024,1440,1920]){await check(`Commitments responsive ${width}`,async()=>{await page.setViewportSize({width,height:900});await page.goto('http://127.0.0.1:4174/financas');await page.getByRole('button',{name:/^Compromissos/}).click();await page.locator('.finance-commitment-card').waitFor();assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));if(width===390||width===1440)await page.screenshot({path:`qa/artifacts/screens/${width}-compromissos.png`,fullPage:true});});}
await page.setViewportSize({width:390,height:844});await page.goto('http://127.0.0.1:4174');await page.locator('h1').waitFor();
await check('Mobile notification activation (mock)',async()=>{await page.getByRole('button',{name:'Abrir menu da conta'}).click();await page.locator('#nexo-account-menu').getByRole('button',{name:'Ativar',exact:true}).click();await page.locator('#nexo-account-menu .nexo-notification-prompt').waitFor({state:'detached'});});
await check('Keyboard focus is visible',async()=>{await page.keyboard.press('Escape');await page.getByLabel('Valor do registro rápido').focus();const state=await page.getByLabel('Valor do registro rápido').evaluate(e=>({outline:getComputedStyle(e).outlineWidth,shadow:getComputedStyle(e).boxShadow}));assert(state.outline==='2px'||state.shadow!=='none');});
await page.setViewportSize({width:1440,height:1000});await page.goto('http://127.0.0.1:4174');
await check('Desktop logout (mock)',async()=>{await page.locator('.nexo-sidebar').getByRole('button',{name:'Sair do NEXO'}).click();await page.waitForURL('**/login');await page.getByRole('button',{name:'Continuar com Google'}).waitFor();await page.getByRole('button',{name:'Continuar com Google'}).click();await page.waitForURL('http://127.0.0.1:4174/');});
for(const width of [390,1440]){await page.setViewportSize({width,height:1000});for(const route of ['home','memorias','lembretes','financas','buscar','configuracoes']){await page.goto('http://127.0.0.1:4174/'+(route==='home'?'':route));await page.locator('h1').waitFor();if(route==='buscar'){await page.getByLabel('Buscar em todo o NEXO').fill('planejamento');await page.locator('.search-result').waitFor();}await page.evaluate(()=>document.fonts.ready);await page.waitForTimeout(700);await page.screenshot({path:`qa/artifacts/screens/${width}-${route}.png`,fullPage:true});}}
const prod=await browser.newPage();for(const width of [320,390,768,1024,1440,1920]){await check(`Real Login responsive ${width}`,async()=>{await prod.setViewportSize({width,height:900});await prod.goto('http://127.0.0.1:4173/login');await prod.getByRole('button',{name:'Continuar com Google'}).waitFor();assert(await prod.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));});}
fs.writeFileSync('qa/artifacts/extra-results.json',JSON.stringify({results},null,2));await browser.close();
