import {fileURLToPath} from 'node:url';
import { chromium } from 'playwright';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import {seed} from './qa-seed.mjs';
process.chdir(fileURLToPath(new URL('../', import.meta.url)));
const browser=await chromium.launch({headless:true,...(process.env.NEXO_TEST_BROWSER ? {executablePath:process.env.NEXO_TEST_BROWSER} : {})});
const context=await browser.newContext({viewport:{width:1440,height:1000},reducedMotion:'reduce'});
const page=await context.newPage();
const results=[];const errors=[];
page.on('pageerror', e=>errors.push(e.message));
page.on('dialog',dialog=>dialog.accept());
async function check(name,fn){try{await fn();results.push({name,status:'pass'});console.log('PASS',name);}catch(e){results.push({name,status:'fail',error:e.message});console.log('FAIL',name,e.message);}}
async function poll(fn){for(let i=0;i<50;i++){if(await fn())return;await page.waitForTimeout(100)}throw Error('Condition timed out')}
async function count(table){return page.evaluate(async t=>(await import('/src/db.ts')).db[t].count(),table)}
async function route(path){await page.goto('http://127.0.0.1:4174'+path);await page.locator('h1').waitFor();await page.waitForTimeout(100)}
fs.mkdirSync('qa/artifacts/screens',{recursive:true});
await route('/');
await check('Home empty states',async()=>{assert(await page.getByText('Nada marcado por enquanto').isVisible());assert(await page.getByText('Nenhuma despesa este mês').isVisible());});
await check('Quick expense: category then amount and submit',async()=>{await page.getByRole('button',{name:'Alimentação',exact:true}).click();await page.getByLabel('Valor do registro rápido').fill('35,50');await page.getByRole('button',{name:'Adicionar',exact:true}).click();await poll(async()=>await count('transactions')===1);assert(await page.getByRole('status').isVisible());});
await check('Quick income: amount then category auto-save',async()=>{await page.getByRole('button',{name:'Ganho',exact:true}).click();await page.getByLabel('Valor do registro rápido').fill('150');await page.getByRole('button',{name:'Salário',exact:true}).click();await poll(async()=>await count('transactions')===2);});
await check('Quick invalid amount adds nothing',async()=>{await page.getByLabel('Valor do registro rápido').fill('-2');await page.getByRole('button',{name:'Salário',exact:true}).click();assert.equal(await count('transactions'),2);});
await check('Ctrl+K opens global search',async()=>{await page.keyboard.press('Control+k');await page.waitForURL('**/buscar');assert(await page.getByLabel('Buscar em todo o NEXO').isVisible());});
await route('/memorias');
await check('Memory creation, search, clear and delete',async()=>{await page.getByLabel('Título',{exact:true}).fill('Memória QA');await page.locator('textarea').fill('Conteúdo persistido QA');await page.getByLabel('Tags',{exact:false}).fill('teste, pessoal');await page.getByRole('button',{name:'Guardar memória',exact:false}).click();await poll(async()=>await count('memories')===1);await page.getByLabel('Pesquisar memórias').fill('persistido');assert(await page.locator('.nexo-memory-card').count()===1);await page.getByLabel('Pesquisar memórias').fill('inexistente');await page.getByText('Nenhuma memória encontrada').waitFor();await page.getByRole('button',{name:'Limpar pesquisa',exact:true}).last().click();await page.getByRole('button',{name:'Excluir memória'}).click();await poll(async()=>await count('memories')===0);});
await route('/lembretes');
await check('Reminder create, complete, reopen and delete',async()=>{await page.getByLabel('Título',{exact:true}).fill('Lembrete QA');await page.getByRole('button',{name:'Criar lembrete'}).click();await poll(async()=>await count('reminders')===1);await page.getByRole('button',{name:'Concluir',exact:true}).click();await page.getByRole('button',{name:'Reabrir',exact:true}).waitFor();await page.getByRole('button',{name:'Reabrir',exact:true}).click();await page.getByRole('button',{name:'Concluir',exact:true}).waitFor();await page.getByRole('button',{name:'Excluir lembrete'}).click();await poll(async()=>await count('reminders')===0);});
await route('/financas');
await check('Finance manual transaction and delete',async()=>{await page.getByLabel('Descrição',{exact:true}).fill('Movimentação QA');await page.getByLabel('Valor',{exact:true}).fill('48,90');await page.getByRole('button',{name:'Registrar movimentação'}).click();await poll(async()=>await count('transactions')===3);await page.locator('.transaction-row').filter({hasText:'Movimentação QA'}).getByRole('button',{name:'Excluir movimentação'}).click();await poll(async()=>await count('transactions')===2);});
await check('Finance quick expense',async()=>{await page.getByRole('button',{name:'Casa',exact:true}).click();await page.getByLabel('Valor do gasto rápido').fill('80');await page.getByRole('button',{name:'Adicionar',exact:true}).click();await poll(async()=>await count('transactions')===3);});
await page.getByRole('button',{name:'Compromissos',exact:true}).click();
await check('Commitment form custom frequency, unlimited and reminders',async()=>{await page.getByLabel('Descrição',{exact:true}).fill('Compromisso QA');await page.getByLabel('Valor de cada pagamento').fill('100');await page.getByLabel('Frequência').selectOption('custom');await page.getByLabel('Repetir a cada quantos dias?').fill('10');await page.getByLabel('Tem quantidade definida de pagamentos').uncheck();await page.getByRole('button',{name:'Criar compromisso'}).click();await poll(async()=>await count('financialCommitments')===1);assert.equal(await count('reminders'),1);assert(await page.getByText('Recorrência contínua').isVisible());});
await check('Commitment pay, pause, resume, cancel and history',async()=>{await page.getByRole('button',{name:'Marcar como pago'}).click();await poll(async()=>await count('transactions')===4);await page.getByRole('button',{name:'Pausar compromisso'}).click();await page.getByRole('button',{name:'Reativar'}).waitFor();await page.getByRole('button',{name:'Reativar'}).click();await page.getByRole('button',{name:'Pausar compromisso'}).waitFor();await page.getByRole('button',{name:'Cancelar compromisso'}).click();await page.getByText('Compromissos encerrados').waitFor();assert(await page.getByText('Cancelado',{exact:true}).isVisible());});
await check('Commitment delete preserves paid transactions',async()=>{await page.getByLabel('Descrição',{exact:true}).fill('Excluir QA');await page.getByLabel('Valor de cada pagamento').fill('50');await page.getByRole('button',{name:'Criar compromisso'}).click();await poll(async()=>await count('financialCommitments')===2);await page.getByRole('button',{name:'Excluir compromisso'}).click();await poll(async()=>await count('financialCommitments')===1);assert.equal(await count('transactions'),4);});
await route('/');await seed(page);await page.waitForTimeout(300);
await check('Activity expand/collapse',async()=>{assert.equal(await page.locator('.nexo-activity-item').count(),4);await page.getByRole('button',{name:/Ver mais/}).click();assert(await page.locator('.nexo-activity-item').count()>4);await page.getByRole('button',{name:'Ver menos'}).click();assert.equal(await page.locator('.nexo-activity-item').count(),4)});
await check('Populated Home retains every section',async()=>{for(const sel of ['.nexo-attention-card','.nexo-next-event','.nexo-category-list','.nexo-stat-grid','.nexo-quick-form','.nexo-quick-links','.nexo-activity-list'])assert(await page.locator(sel).isVisible());});
await check('Search across modules',async()=>{await route('/buscar');for(const term of ['Ideias','planejamento','Cinema','internet']){await page.getByLabel('Buscar em todo o NEXO').fill(term);await poll(async()=>await page.locator('.search-result').count()>0);}});
await check('Desktop sidebar links and active indicator',async()=>{for(const [label,path] of [['Início','/'],['Memórias','/memorias'],['Lembretes','/lembretes'],['Finanças','/financas'],['Buscar','/buscar']]){await page.getByRole('navigation',{name:'Navegação principal',exact:true}).getByRole('link',{name:label,exact:true}).click();await page.waitForURL('http://127.0.0.1:4174'+path);assert.equal(await page.locator('.desktop-nav [aria-current="page"]').count(),1);}});
await check('Desktop profile and notification prompt dismiss',async()=>{assert(await page.locator('.profile-info').getByText('Marina Costa').isVisible());await page.locator('.nexo-sidebar').getByRole('button',{name:'Fechar convite de notificações'}).click();await page.reload();await page.locator('h1').waitFor();assert.equal(await page.locator('.nexo-sidebar .nexo-notification-prompt').count(),0);});
await check('Settings notification activation (simulated service)',async()=>{await page.locator('.nexo-sidebar').getByRole('button',{name:'Configurações',exact:true}).click();await page.waitForURL('**/configuracoes');await page.getByRole('button',{name:'Ativar notificações'}).click();await page.getByText('Notificações ativas',{exact:true}).waitFor();});
const routes=['/','/memorias','/lembretes','/financas','/buscar','/configuracoes'];
for(const width of [320,390,768,1024,1440,1920]){await page.setViewportSize({width,height:900});for(const path of routes){await check(`Responsive ${width}px ${path}`,async()=>{await route(path);if(path==='/buscar')await page.getByLabel('Buscar em todo o NEXO').fill('a');const dims=await page.evaluate(()=>({scroll:document.documentElement.scrollWidth,view:innerWidth}));assert(dims.scroll<=dims.view,JSON.stringify(dims));if(width===390||width===1440)await page.screenshot({path:`qa/artifacts/screens/${width}-${path==='/'?'home':path.slice(1)}.png`,fullPage:true});});}}
await page.setViewportSize({width:390,height:844});await route('/');
await check('Mobile navigation all five routes',async()=>{for(const [label,path] of [['Memórias','/memorias'],['Lembretes','/lembretes'],['Finanças','/financas'],['Buscar','/buscar'],['Início','/']]){await page.locator('.mobile-nav').getByRole('link',{name:label,exact:true}).click();await page.waitForURL('http://127.0.0.1:4174'+path);assert.equal(await page.locator('.mobile-nav [aria-current="page"]').count(),1);}});
await check('Mobile account Escape, outside click and settings',async()=>{const avatar=page.getByRole('button',{name:'Abrir menu da conta'});await avatar.click();await page.locator('#nexo-account-menu').waitFor();await page.keyboard.press('Escape');await poll(async()=>await page.locator('#nexo-account-menu').count()===0);assert(await avatar.evaluate(e=>e===document.activeElement));await avatar.click();await page.mouse.click(8, 500);await poll(async()=>await page.locator('#nexo-account-menu').count()===0);await avatar.click();await page.locator('#nexo-account-menu').getByRole('button',{name:'Configurações'}).click();await page.waitForURL('**/configuracoes');await poll(async()=>await page.locator('#nexo-account-menu').count()===0);});
await check('Mobile logout and Google entry (simulated auth)',async()=>{await page.getByRole('button',{name:'Abrir menu da conta'}).click();await page.locator('#nexo-account-menu').getByRole('button',{name:'Sair do NEXO'}).click();await page.waitForURL('**/login');await page.screenshot({path:'qa/artifacts/screens/390-login.png',fullPage:true});await page.getByRole('button',{name:'Continuar com Google'}).click();await page.waitForURL('http://127.0.0.1:4174/');});
await check('Long strings and large amounts have no horizontal overflow',async()=>{await page.evaluate(async()=>{const {db}=await import('/src/db.ts');await db.memories.add({title:'TítuloExtenso'.repeat(20),content:'ConteúdoSemEspaços'.repeat(80),tags:['tag'.repeat(40)],createdAt:new Date().toISOString(),updatedAt:new Date().toISOString()});await db.transactions.add({description:'Descrição'.repeat(50),amount:123456789.99,type:'income',category:'Salário',occurredAt:new Date().toISOString(),createdAt:new Date().toISOString()});});for(const path of ['/','/memorias','/financas','/buscar']){await route(path);if(path==='/buscar')await page.getByLabel('Buscar em todo o NEXO').fill('Título');assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),path);}});
await check('No uncaught client errors',async()=>assert.deepEqual(errors,[]));
const prod=await browser.newPage({viewport:{width:1440,height:1000}});
await check('Production bundle: protected routes redirect to real Login',async()=>{for(const path of routes){await prod.goto('http://127.0.0.1:4173'+path);await prod.waitForURL('**/login');await prod.getByRole('button',{name:'Continuar com Google'}).waitFor();}await prod.screenshot({path:'qa/artifacts/screens/1440-login-production.png',fullPage:true});});
fs.writeFileSync('qa/artifacts/results.json',JSON.stringify({results,errors},null,2));await browser.close();
console.log('TOTAL',results.length,'FAIL',results.filter(r=>r.status==='fail').length);


process.exitCode = results.some(result => result.status === 'fail') ? 1 : 0;
